# === Obecné nastavení (platí pro všechny jaily) ===
[DEFAULT]
ignoreip = 127.0.0.1/8 ::1 192.168.0.0/16
bantime  = 1h
findtime = 10m
maxretry = 3
backend  = systemd

# === Django login pokusy ===
[django-login]
enabled  = true
filter   = django-login
logpath  = /var/www/RHENUS/Demo/logs/login_failures.log
maxretry = 5
findtime = 5m
bantime  = 1h

# === NGINX HTTP Auth ===
[nginx-http-auth]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/error.log
maxretry = 5
findtime = 5m
bantime  = 1h

# === SSHD ===
[sshd]
enabled  = true
port     = 2222
logpath  = %(sshd_log)s
backend  = systemd
maxretry = 3
bantime  = 1h
findtime = 3m
