# Generated by Django 5.2 on 2025-04-16 15:48

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=32, verbose_name="Společnost")),
                ("city", models.CharField(max_length=32, verbose_name="Město")),
                (
                    "region",
                    models.CharField(blank=True, max_length=32, verbose_name="Region"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=64, verbose_name="E-mail"),
                ),
                (
                    "web",
                    models.CharField(blank=True, max_length=64, verbose_name="Web"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktivní")),
                (
                    "price_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Cena za hodinu",
                    ),
                ),
                (
                    "price_per_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Cena za km",
                    ),
                ),
                ("termin", models.TextField(blank=True, verbose_name="Termín")),
                ("notes", models.TextField(blank=True, verbose_name="Poznámka")),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Číslo zakázky"
                    ),
                ),
                ("mandant", models.CharField(max_length=4, verbose_name="Mandant")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("New", "Nový"),
                            ("Adviced", "Zatermínováno"),
                            ("Realized", "Realizováno"),
                            ("Canceled", "Zrušeno"),
                            ("Billed", "Vyúčtovaný"),
                        ],
                        default="New",
                        max_length=32,
                        verbose_name="Stav",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=64, verbose_name="Jméno zákazníka"),
                ),
                ("zip_code", models.CharField(max_length=5, verbose_name="PSČ")),
                (
                    "evidence_termin",
                    models.DateField(null=True, verbose_name="Termín evidence"),
                ),
                (
                    "delivery_termin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Termín doručení"
                    ),
                ),
                (
                    "team_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Empty", "Nevyplneno"),
                            ("By customer", "Zákazníkem"),
                            ("By delivery crew", "Dopravcem"),
                            ("By assembly crew", "Montážníky"),
                        ],
                        default="Empty",
                        max_length=32,
                        verbose_name="Realizace kým",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Poznámky")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Vytvořeno"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Upraveno"),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app_sprava_montazi.team",
                        verbose_name="Montážní tým",
                    ),
                ),
            ],
        ),
    ]
