# Generated by Django 5.2 on 2025-05-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Množství"),
        ),
    ]
