# Generated by Django 5.2 on 2025-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="name",
            field=models.CharField(max_length=32, verbose_name="Název artiklu"),
        ),
    ]
