# Generated by Django 5.2 on 2025-05-01 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="team",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"active": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="app_sprava_montazi.team",
                verbose_name="Montážní tým",
            ),
        ),
    ]
