# Generated by Django 5.2 on 2025-05-13 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="app_sprava_montazi.order",
                verbose_name="zakazka",
            ),
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("called_at", models.DateTimeField(verbose_name="Čas volání")),
                ("note", models.TextField(blank=True, verbose_name="Poznámka")),
                (
                    "was_successful",
                    models.BooleanField(default=False, verbose_name="Dovoláno"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to="app_sprava_montazi.client",
                        verbose_name="Zákazník",
                    ),
                ),
            ],
        ),
    ]
