# Generated by Django 5.2 on 2025-07-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='team_type',
            field=models.CharField(blank=True, choices=[('By_customer', 'Zákazníkem'), ('By_delivery_crew', 'Dopravcem'), ('By_assembly_crew', 'Montážníky')], default='By_assembly_crew', max_length=32, verbose_name='Realizace kým'),
        ),
        migrations.AlterField(
            model_name='order',
            name='team_type',
            field=models.CharField(blank=True, choices=[('By_customer', 'Zákazníkem'), ('By_delivery_crew', 'Dopravcem'), ('By_assembly_crew', 'Montážníky')], default='By_assembly_crew', max_length=32, verbose_name='Realizace kým'),
        ),
    ]
