# Generated by Django 5.2 on 2025-04-28 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_number"]},
        ),
    ]
