# Generated by Django 5.2 on 2025-04-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=75, verbose_name="Jméno zákazníka"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "Nový"),
                    ("Adviced", "Zatermínováno"),
                    ("Realized", "Realizováno"),
                    ("Billed", "Vyúčtovaný"),
                    ("Canceled", "Zrušeno"),
                    ("Hidden", "Skryto"),
                ],
                default="New",
                max_length=32,
                verbose_name="Stav",
            ),
        ),
    ]
