# Generated by Django 5.2 on 2025-04-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="mandant",
            field=models.CharField(
                default="SCCZ", max_length=4, verbose_name="Mandant"
            ),
            preserve_default=False,
        ),
    ]
