# Generated by Django 5.2 on 2025-07-24 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('name', 'zip_code')},
        ),
    ]
