# Generated by Django 5.2 on 2025-05-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0002_alter_article_order_calllog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="called_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Čas volání"),
        ),
    ]
