# Generated by Django 5.2 on 2025-05-02 19:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0002_alter_order_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=17, region=None, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=17, region=None, verbose_name="Telefon"
            ),
        ),
    ]
