# Generated by Django 5.2 on 2025-07-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0002_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='AppSetting',
        ),
    ]
