# Generated by Django 5.2 on 2025-05-28 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0002_calllog_user_historicalcalllog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Množství",
            ),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(99),
                ],
                verbose_name="Množství",
            ),
        ),
    ]
