# Generated by Django 5.2 on 2025-10-11 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0002_financecostitem_financerevenueitem_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financerevenueitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="historicalfinancecostitem",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalfinancecostitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="historicalfinancecostitem",
            name="team",
        ),
        migrations.RemoveField(
            model_name="historicalfinancerevenueitem",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalfinancerevenueitem",
            name="order",
        ),
        migrations.DeleteModel(
            name="FinanceCostItem",
        ),
        migrations.DeleteModel(
            name="FinanceRevenueItem",
        ),
        migrations.DeleteModel(
            name="HistoricalFinanceCostItem",
        ),
        migrations.DeleteModel(
            name="HistoricalFinanceRevenueItem",
        ),
    ]
