# Generated by Django 5.2 on 2025-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0003_alter_calllog_called_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="was_successful",
            field=models.CharField(
                choices=[("Success", "Úspěšný"), ("Failed", "Neúspěšný")],
                default="Failed",
                verbose_name="Dovoláno",
            ),
        ),
    ]
