# Generated by Django 5.2 on 2025-05-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0003_alter_article_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalteam",
            name="email",
            field=models.EmailField(max_length=64, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="team",
            name="email",
            field=models.EmailField(max_length=64, verbose_name="E-mail"),
        ),
    ]
