# Generated by Django 5.2 on 2025-07-25 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0003_alter_historicalorder_team_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_sofa',
        ),
        migrations.RemoveField(
            model_name='article',
            name='price',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='is_sofa',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='price',
        ),
    ]
