# Generated by Django 5.2 on 2025-05-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0003_alter_client_phone_alter_team_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Množství"),
        ),
    ]
