# Generated by Django 5.2 on 2025-05-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0004_alter_article_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                max_length=10,
                null=True,
                verbose_name="Cena",
            ),
        ),
    ]
