# Generated by Django 5.2 on 2025-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0004_remove_article_is_sofa_remove_article_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='naklad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kolik zakázka stála (výdaje)', max_digits=10, null=True, verbose_name='Náklad'),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='vynos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kolik za zakázku dostanu zaplaceno (příjem)', max_digits=10, null=True, verbose_name='Výnos'),
        ),
        migrations.AddField(
            model_name='order',
            name='naklad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kolik zakázka stála (výdaje)', max_digits=10, null=True, verbose_name='Náklad'),
        ),
        migrations.AddField(
            model_name='order',
            name='vynos',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kolik za zakázku dostanu zaplaceno (příjem)', max_digits=10, null=True, verbose_name='Výnos'),
        ),
    ]
