# Generated by Django 6.0.2 on 2026-03-02 17:34

import app_sprava_montazi.encryption
from django.db import migrations


def encrypt_existing_data(apps, schema_editor):
    """
    Zašifruje existující plaintext data v Client a HistoricalClient.
    Používá přímý SQL update protože ORM field.from_db_value() by
    dešifrovalo data ihned po načtení.
    """
    from app_sprava_montazi.encryption import encrypt_str, is_encrypted

    db_alias = schema_editor.connection.alias

    # --- Client tabulka ---
    Client = apps.get_model("app_sprava_montazi", "Client")
    for client in Client.objects.using(db_alias).all().iterator():
        changed = False
        for field_name in ("phone", "email", "street"):
            value = getattr(client, field_name)
            if value and not is_encrypted(str(value)):
                setattr(client, field_name, encrypt_str(str(value)))
                changed = True
        if changed:
            Client.objects.using(db_alias).filter(pk=client.pk).update(
                phone=client.phone,
                email=client.email,
                street=client.street,
            )

    # --- HistoricalClient tabulka ---
    HistoricalClient = apps.get_model("app_sprava_montazi", "HistoricalClient")
    for hc in HistoricalClient.objects.using(db_alias).all().iterator():
        changed = False
        for field_name in ("phone", "email", "street"):
            value = getattr(hc, field_name)
            if value and not is_encrypted(str(value)):
                setattr(hc, field_name, encrypt_str(str(value)))
                changed = True
        if changed:
            HistoricalClient.objects.using(db_alias).filter(pk=hc.pk).update(
                phone=hc.phone,
                email=hc.email,
                street=hc.street,
            )


def decrypt_existing_data(apps, schema_editor):
    """
    Reverzní migrace: dešifruje data zpět do plaintextu.
    """
    from app_sprava_montazi.encryption import decrypt_str, is_encrypted

    db_alias = schema_editor.connection.alias

    Client = apps.get_model("app_sprava_montazi", "Client")
    for client in Client.objects.using(db_alias).all().iterator():
        changed = False
        for field_name in ("phone", "email", "street"):
            value = getattr(client, field_name)
            if value and is_encrypted(str(value)):
                setattr(client, field_name, decrypt_str(str(value)))
                changed = True
        if changed:
            Client.objects.using(db_alias).filter(pk=client.pk).update(
                phone=client.phone,
                email=client.email,
                street=client.street,
            )

    HistoricalClient = apps.get_model("app_sprava_montazi", "HistoricalClient")
    for hc in HistoricalClient.objects.using(db_alias).all().iterator():
        changed = False
        for field_name in ("phone", "email", "street"):
            value = getattr(hc, field_name)
            if value and is_encrypted(str(value)):
                setattr(hc, field_name, decrypt_str(str(value)))
                changed = True
        if changed:
            HistoricalClient.objects.using(db_alias).filter(pk=hc.pk).update(
                phone=hc.phone,
                email=hc.email,
                street=hc.street,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0004_financecostitem_financerevenueitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=app_sprava_montazi.encryption.EncryptedEmailField(blank=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=app_sprava_montazi.encryption.EncryptedCharField(blank=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='client',
            name='street',
            field=app_sprava_montazi.encryption.EncryptedCharField(blank=True, verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='email',
            field=app_sprava_montazi.encryption.EncryptedEmailField(blank=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='phone',
            field=app_sprava_montazi.encryption.EncryptedCharField(blank=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='street',
            field=app_sprava_montazi.encryption.EncryptedCharField(blank=True, verbose_name='Ulice'),
        ),
        # --- Data migrace: zašifruj existující plaintext záznamy ---
        migrations.RunPython(
            encrypt_existing_data,
            decrypt_existing_data,
        ),
    ]
