# Generated by Django 5.2 on 2025-05-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0004_alter_calllog_was_successful"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="calllog",
            options={"ordering": ["-called_at"]},
        ),
        migrations.AlterField(
            model_name="calllog",
            name="was_successful",
            field=models.CharField(
                choices=[("Success", "Úspěšný"), ("Failed", "Neúspěšný")],
                verbose_name="Dovoláno",
            ),
        ),
    ]
