# Generated by Django 5.2 on 2025-08-09 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0005_historicalorder_naklad_historicalorder_vynos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMontazImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='montage_images/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Cas ulozeni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='montage_images', to='app_sprava_montazi.order', verbose_name='Fotky z montaze')),
            ],
        ),
    ]
