# Generated by Django 5.2 on 2025-05-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0005_alter_article_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Cena",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="quantity",
            field=models.PositiveIntegerField(max_length=3, verbose_name="Množství"),
        ),
    ]
