# Generated by Django 5.2 on 2025-05-30 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0005_historicalorderpdf_orderpdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HistoricalOrderPDF",
            new_name="HistoricalOrderPDFStorage",
        ),
        migrations.RenameModel(
            old_name="OrderPDF",
            new_name="OrderPDFStorage",
        ),
        migrations.AlterModelOptions(
            name="historicalorderpdfstorage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical order pdf storage",
                "verbose_name_plural": "historical order pdf storages",
            },
        ),
    ]
