# Generated by Django 5.2 on 2025-05-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_sprava_montazi",
            "0005_alter_calllog_options_alter_calllog_was_successful",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="note",
            field=models.TextField(verbose_name="Poznámka"),
        ),
    ]
