# Generated by Django 6.0.2 on 2026-03-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0005_encrypt_client_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Název politiky')),
                ('retention_days', models.PositiveIntegerField(choices=[(365, '1 rok'), (730, '2 roky'), (1095, '3 roky'), (1825, '5 let'), (2555, '7 let'), (3650, '10 let')], default=1825, help_text='Počet dní od poslední zakázky zákazníka', verbose_name='Doba uchovávání (dní)')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('auto_anonymize', models.BooleanField(default=False, help_text='Po uplynutí doby automaticky anonymizovat osobní údaje', verbose_name='Automatická anonymizace')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Politika uchovávání dat',
                'verbose_name_plural': 'Politiky uchovávání dat',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum souhlasu'),
        ),
        migrations.AddField(
            model_name='client',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Zákazník udělil souhlas dle GDPR čl. 6', verbose_name='Souhlas se zpracováním'),
        ),
        migrations.AddField(
            model_name='client',
            name='data_retention_until',
            field=models.DateField(blank=True, help_text='Po tomto datu budou osobní údaje automaticky anonymizovány', null=True, verbose_name='Uchovávat data do'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='Osobní údaje byly smazány dle GDPR', verbose_name='Anonymizováno'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum souhlasu'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Zákazník udělil souhlas dle GDPR čl. 6', verbose_name='Souhlas se zpracováním'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='data_retention_until',
            field=models.DateField(blank=True, help_text='Po tomto datu budou osobní údaje automaticky anonymizovány', null=True, verbose_name='Uchovávat data do'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='is_anonymized',
            field=models.BooleanField(default=False, help_text='Osobní údaje byly smazány dle GDPR', verbose_name='Anonymizováno'),
        ),
    ]
