# Generated by Django 5.2 on 2025-07-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0005_historicalappsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='mail_team_sended',
            field=models.CharField(blank=True, verbose_name='jakemu tymu byl poslan email'),
        ),
        migrations.AddField(
            model_name='order',
            name='mail_team_sended',
            field=models.CharField(blank=True, verbose_name='jakemu tymu byl poslan email'),
        ),
    ]
