# Generated by Django 5.2 on 2025-05-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0006_alter_calllog_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="note",
            field=models.TextField(blank=True, verbose_name="Poznámka"),
        ),
    ]
