# Generated by Django 5.2 on 2025-08-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0006_ordermontazimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermontazimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
