# Generated by Django 5.2 on 2025-07-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0006_historicalorder_mail_team_sended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderpdfstorage',
            name='team',
            field=models.CharField(default='no team', max_length=32, verbose_name='montazni tym'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpdfstorage',
            name='team',
            field=models.CharField(default='', max_length=32, verbose_name='montazni tym'),
            preserve_default=False,
        ),
    ]
