# Generated by Django 5.2 on 2025-05-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0006_alter_article_price_alter_article_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Množství"),
        ),
    ]
