# Generated by Django 5.2 on 2025-06-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_sprava_montazi",
            "0006_rename_historicalorderpdf_historicalorderpdfstorage_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_sofa",
            field=models.BooleanField(
                default=False, verbose_name="Je to sedaci souprava?"
            ),
        ),
        migrations.AddField(
            model_name="historicalarticle",
            name="is_sofa",
            field=models.BooleanField(
                default=False, verbose_name="Je to sedaci souprava?"
            ),
        ),
    ]
