# Generated by Django 5.2 on 2025-08-10 09:43

import app_sprava_montazi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0007_ordermontazimage_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermontazimage',
            name='image',
            field=models.FileField(upload_to=app_sprava_montazi.models.upload_to_order_folder),
        ),
    ]
