# Generated by Django 5.2 on 2025-06-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0007_article_is_sofa_historicalarticle_is_sofa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_sofa",
            field=models.BooleanField(default=False, verbose_name="Sedačka?"),
        ),
        migrations.AlterField(
            model_name="historicalarticle",
            name="is_sofa",
            field=models.BooleanField(default=False, verbose_name="Sedačka?"),
        ),
    ]
