# Generated by Django 5.2 on 2025-08-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0008_alter_ordermontazimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorderbackprotocol',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Popis obrazku'),
        ),
        migrations.AddField(
            model_name='orderbackprotocol',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Popis obrazku'),
        ),
    ]
