# Generated by Django 5.2 on 2025-06-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0008_alter_article_is_sofa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalorder",
            name="mail_datum_sended",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Protocol mail odeslan"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="mail_datum_sended",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Protocol mail odeslan"
            ),
        ),
    ]
