# Generated by Django 5.2 on 2025-08-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sprava_montazi', '0009_historicalorderbackprotocol_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermontazimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Popis obrazku'),
        ),
    ]
