# Generated by Django 5.2 on 2025-06-17 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_sprava_montazi", "0010_alter_orderpdfstorage_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderBackProtocolToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="app_sprava_montazi.order",
                    ),
                ),
            ],
        ),
    ]
